import os

def setupLogConfig():
    rootDirectory = os.path.abspath(os.path.dirname(__file__))
    logFileDir = os.path.join(rootDirectory, 'logs')
    defaultLogFile = 'dga.log'
    buf = "# DO NOT EDIT THIS FILE BY HAND. AUTO GENERATED FROM SETUP\n" + \
    "LOG_DIRECTORY='"+logFileDir+"'\n"
    logFilePath = os.path.join(logFileDir, defaultLogFile)
    if not os.path.exists(os.path.dirname(logFilePath)):
        os.makedirs(os.path.dirname(logFilePath))
    logConfigFile = os.path.join(rootDirectory, 'config', 'logConfig.py')
    f = open(logConfigFile, 'w+')
    f.write(buf)
    f.close() 

def setupNetworkConfig():
    pass

if __name__ == '__main__':
    setupLogConfig()
    setupNetworkConfig()
