HOST_IP = ''
HOST_PORT = 2020
MESSAGE_LENGTH_DIGITS = 4
MESSAGE_DELIMITER = '$'
MESSAGE_DELIMITER_BANG = '#'
MESSAGE_RECEIPT_SUCCESS = 'SUCCESS'
MESSAGE_UNRECOGNIZED = 'UNRECOGNIZED'
MAX_BACKLOG_CONN = 5
