MAX_BACKLOG_CONN = 5
MAX_RETRIES = 50
MESSAGE_LENGTH_DIGITS = 4
MESSAGE_DELIMITER = '$'
MESSAGE_DELIMITER_BANG = '#'
MESSAGE_RECEIPT_SUCCESS = 'SUCCESS'
MESSAGE_UNRECOGNIZED = 'UNRECOGNIZED'
UNSUCCESSFUL_GET_TASK_WAIT_TIME = 0.01
